//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppToTrip.Recursos.RecursosIdioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class appRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal appRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppToTrip.Recursos.RecursosIdioma.appRecursos", typeof(appRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto los términos y condiciones de las políticas de tratamiento de datos..
        /// </summary>
        public static string aceptaTerminosYCondiciones {
            get {
                return ResourceManager.GetString("aceptaTerminosYCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string apellido {
            get {
                return ResourceManager.GetString("apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ic_lg_es.
        /// </summary>
        public static string banderaIdioma {
            get {
                return ResourceManager.GetString("banderaIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar mi cuenta.
        /// </summary>
        public static string BuscarCuenta {
            get {
                return ResourceManager.GetString("BuscarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerca de mí.
        /// </summary>
        public static string cercaDeMi {
            get {
                return ResourceManager.GetString("cercaDeMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circuitos.
        /// </summary>
        public static string circuitos {
            get {
                return ResourceManager.GetString("circuitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ingresado no es válido..
        /// </summary>
        public static string codigoNOValido {
            get {
                return ResourceManager.GetString("codigoNOValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprueba tu conexión a internet.
        /// </summary>
        public static string compruebaTuConexionAInternet {
            get {
                return ResourceManager.GetString("compruebaTuConexionAInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string continuar {
            get {
                return ResourceManager.GetString("continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Circuito.
        /// </summary>
        public static string crearCircuito {
            get {
                return ResourceManager.GetString("crearCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string crearCuenta {
            get {
                return ResourceManager.GetString("crearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta no encontrada con este dispositivo.
        /// </summary>
        public static string cuentaNoEncontradaConEsteDispositivo {
            get {
                return ResourceManager.GetString("cuentaNoEncontradaConEsteDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del correo electrónico es incorrecto.
        /// </summary>
        public static string elFormatoDeCorreoEsIncorrecto {
            get {
                return ResourceManager.GetString("elFormatoDeCorreoEsIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del nombre es incorrecto.
        /// </summary>
        public static string elFormatoDelNombreEsIncorrecto {
            get {
                return ResourceManager.GetString("elFormatoDelNombreEsIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del télefono es incorrecto.
        /// </summary>
        public static string elFormatoDelTelefonoEsIncorrecto {
            get {
                return ResourceManager.GetString("elFormatoDelTelefonoEsIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya está registrado.
        /// </summary>
        public static string elUsuarioYaEstaRegistrado {
            get {
                return ResourceManager.GetString("elUsuarioYaEstaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estamos cargando información en este momento, revisa más tarde..
        /// </summary>
        public static string estamosCargandoInformacion {
            get {
                return ResourceManager.GetString("estamosCargandoInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string ingresar {
            get {
                return ResourceManager.GetString("ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el código.
        /// </summary>
        public static string ingresarCodigo {
            get {
                return ResourceManager.GetString("ingresarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar con Facebook.
        /// </summary>
        public static string ingresarConFacebook {
            get {
                return ResourceManager.GetString("ingresarConFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar con Google.
        /// </summary>
        public static string ingresarConGoogle {
            get {
                return ResourceManager.GetString("ingresarConGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu correo electrónico para buscar tu cuenta..
        /// </summary>
        public static string introduceCorreo {
            get {
                return ResourceManager.GetString("introduceCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de 4 dígitos que se te envió a .
        /// </summary>
        public static string labelCodigo4Digitos {
            get {
                return ResourceManager.GetString("labelCodigo4Digitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el número de días y estaremos encantados de crear una experiencia inolvidable para ti en .
        /// </summary>
        public static string labelCrearCircuito {
            get {
                return ResourceManager.GetString("labelCrearCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Macro.
        /// </summary>
        public static string macro {
            get {
                return ResourceManager.GetString("macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dejes campos vacíos.
        /// </summary>
        public static string noDejesCamposVacios {
            get {
                return ResourceManager.GetString("noDejesCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró su ubicación.
        /// </summary>
        public static string noSeEncontroUbicacion {
            get {
                return ResourceManager.GetString("noSeEncontroUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el número de días.
        /// </summary>
        public static string NumDias {
            get {
                return ResourceManager.GetString("NumDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de celular.
        /// </summary>
        public static string numeroCelular {
            get {
                return ResourceManager.GetString("numeroCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opps! Algo paso.
        /// </summary>
        public static string oppsAlgoPaso {
            get {
                return ResourceManager.GetString("oppsAlgoPaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Política de privacidad.
        /// </summary>
        public static string politicaDePrivacidad {
            get {
                return ResourceManager.GetString("politicaDePrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupera tu cuenta.
        /// </summary>
        public static string recuperarTuCuenta {
            get {
                return ResourceManager.GetString("recuperarTuCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        public static string reenviarCodigo {
            get {
                return ResourceManager.GetString("reenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string registrarme {
            get {
                return ResourceManager.GetString("registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registra tus datos.
        /// </summary>
        public static string registraTusDatos {
            get {
                return ResourceManager.GetString("registraTusDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        public static string reintentar {
            get {
                return ResourceManager.GetString("reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione número de días .
        /// </summary>
        public static string seleccioneDia {
            get {
                return ResourceManager.GetString("seleccioneDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una categoria.
        /// </summary>
        public static string seleccioneUnaCategoria {
            get {
                return ResourceManager.GetString("seleccioneUnaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un destino.
        /// </summary>
        public static string seleccioneUnDestino {
            get {
                return ResourceManager.GetString("seleccioneUnDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un macro.
        /// </summary>
        public static string seleccioneUnMacro {
            get {
                return ResourceManager.GetString("seleccioneUnMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitios.
        /// </summary>
        public static string sitios {
            get {
                return ResourceManager.GetString("sitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos y condiciones.
        /// </summary>
        public static string terminosYcondiciones {
            get {
                return ResourceManager.GetString("terminosYcondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        public static string textAutor {
            get {
                return ResourceManager.GetString("textAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar Circuito.
        /// </summary>
        public static string textComprarCircuito {
            get {
                return ResourceManager.GetString("textComprarCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string textDescripcion {
            get {
                return ResourceManager.GetString("textDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string textDireccion {
            get {
                return ResourceManager.GetString("textDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        public static string textDuracion {
            get {
                return ResourceManager.GetString("textDuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipamiento.
        /// </summary>
        public static string textEquipamiento {
            get {
                return ResourceManager.GetString("textEquipamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario.
        /// </summary>
        public static string textHorario {
            get {
                return ResourceManager.GetString("textHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Circuito.
        /// </summary>
        public static string textIniciarCircuito {
            get {
                return ResourceManager.GetString("textIniciarCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string textRango {
            get {
                return ResourceManager.GetString("textRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendaciones.
        /// </summary>
        public static string textRecomendaciones {
            get {
                return ResourceManager.GetString("textRecomendaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        public static string textReintentar {
            get {
                return ResourceManager.GetString("textReintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string textTelefono {
            get {
                return ResourceManager.GetString("textTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string textUbicacion {
            get {
                return ResourceManager.GetString("textUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante.
        /// </summary>
        public static string tiempoRestante {
            get {
                return ResourceManager.GetString("tiempoRestante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traductor.
        /// </summary>
        public static string traductor {
            get {
                return ResourceManager.GetString("traductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string volver {
            get {
                return ResourceManager.GetString("volver", resourceCulture);
            }
        }
    }
}
